version: '3.8'
services:

  storage:
    image: app
    build: .
    container_name: storage
    env_file:
      - .env
    ports:
      - "8001:8001"

  memcached:
    image: memcached
    container_name: memcached
    ports:
      - "11211:11211"
